server:
  port: 8081

spring:
  application:
    name: backend

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    probes:
      enabled: true

application:
  messaging:
    rpc-topic-exchange: "unkai.rpc.exchange"
    request-queue: "unkai.request.queue"
    request-routing-key: "unkai.request"